### ISSUE TITLE
Thanks for putting up a mirror

### ISSUE THREAD

**Issue by unixorn** [zdharma-continuum/fast-syntax-highlighting#1]
Thanks for putting up a mirror. I'm updating [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) to point at your mirror.

**Comment by vimpostor** [comment]
Is there any news on what happened to @psprint and https://github.com/zdharma?

**Comment by alichtman** [comment]
I don't have any news. I sent him an email a few days ago and it bounced.
