### ISSUE TITLE
Competing repo?

### ISSUE THREAD

**Issue by gwerbin** [zdharma-continuum/fast-syntax-highlighting#12]
What is the difference between this repo and https://github.com/z-shell/fast-syntax-highlighting?

**Comment by pschmitt** [comment]
Not much besides the "ownership", I obviously cannot vouch for the z-shell though and wouldn't advise using any of the z-shell repos but that's just my opinion ;)

**Comment by alichtman** [comment]
Seems like there are a few recent commits on it. I personally use the repo I own

**Comment by gwerbin** [comment]
@pschmitt @alichtman thanks. I am aware that zdharma-continuum is an attempt at keeping the zdharma projects alive in a more "community-oriented" fashion.

But what is this z-shell user/group? It appears to be new, and they don't seem to have any equivalent of <https://github.com/zdharma-continuum/I_WANT_TO_HELP>. Is it a former member of the zdharma-continuum group? Someone opposed to how the zdharma situation was handled?

It might be useful if you explained *why* you recommend avoiding them, other than "they aren't us".

**Comment by alichtman** [comment]
We're not recommending *not using their fork*. It's just a fork that we don't manage or monitor. Feel free to use it if you'd like.

**Comment by vimpostor** [comment]
Looks like there is an update on this. The https://github.com/zdharma/fast-syntax-highlighting repo just got created again and now points as a fork to above mentioned https://github.com/z-shell/fast-syntax-highlighting. So it looks like it may have been wise to not recommend the z-shell group, if it is really owned by @psprint .
I have created an issue at https://github.com/z-shell/fast-syntax-highlighting/issues/8 to get an official reply from whoever z-shell is on this, but if it really is the real zdharma I don't see how we can trust him on not deleting the repo again.

If zdharma will be doing real progress in the repo over there, we can still manually handpick and port over his patches to this repo after all.

**Comment by alichtman** [comment]
> Hi
> 
> Just to clarify the authorship issue – I'm not the owner of the new zdharma group. 
> 
> Thank you for continuing zdharma at @zdharma-continuum. I can say that you have my blessing.

I'm glad you're alive and well :) If you'd ever like to contribute to the project again, you're more than welcome.
