### ISSUE TITLE
Very low speed on WSL2

### ISSUE THREAD

**Issue by namelessshere** [zdharma-continuum/fast-syntax-highlighting#13]
After installing the plugin typing in the shell became very slow. There is a delay after each typed letter. [`zsh-syntax-highlighting`](https://github.com/zsh-users/zsh-syntax-highlighting) has [the same issue](https://github.com/zsh-users/zsh-syntax-highlighting/issues/790).

**Details:**

- WSL2, Debian Sid,
- Zsh 5.8,
- Fast Syntax Highlighting 1.55,
- Tested on [Windows Terminal](https://github.com/microsoft/terminal) and [Fluent Terminal](https://github.com/felixse/FluentTerminal).

**Comment by jcwillox** [comment]
Yeah, I have the same issue particularly with large blocks of code. This type of issue is actually pretty common with WSL, and it usually comes back to path lookups, by default (you can disable it) the windows system path is added to WSLs $PATH, this adds effectively a networked drive with several folders containing a large number of files, this drastically slows down PATH lookups. Often a simple solution is to remove all folders starting with `/mnt/c` from the path when the user is running WSL (can check for `WSL_DISTRO_NAME`), for programs that do not need to search windows paths.

This is a little bash snippet to remove the slow windows paths, not sure how useful it will be in the context of this script, but removing those paths does fix the speed.

```bash
PATH=$(echo $PATH | sed s/:/\\n/g | grep -v '/mnt/c' | sed ':a;N;$!ba;s/\n/:/g')
```

**Comment by namelessshere** [comment]
Thank you for your reply and sorry for noticing so late. Will defenitely try this and tell you about the result when I have some free time.

**Comment by namelessshere** [comment]
Thanks! It helped!

**Comment by jcwillox** [comment]
Great, but that was really just an example, WSL actually has a built-in [option](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) to disable adding windows PATHs to WSL's PATH, but this isn't really ideal as accessing windows executables via PATH is often useful. Ideally, this would be built into fast-syntax-highlighting somehow.

I suppose an alternative for the end-user is to disable adding windows PATHs and instead to use a whitelist approach and create aliases pointing to the windows executables that you want to access. A benefit of this approach is that it would solve the slow path issue for all affected applications.

**Comment by BigTear** [comment]
> Great, but that was really just an example, WSL actually has a built-in [option](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) to disable adding windows PATHs to WSL's PATH, but this isn't really ideal as accessing windows executables via PATH is often useful. Ideally, this would be built into fast-syntax-highlighting somehow.
> 
> I suppose an alternative for the end-user is to disable adding windows PATHs and instead to use a whitelist approach and create aliases pointing to the windows executables that you want to access. A benefit of this approach is that it would solve the slow path issue for all affected applications.

Can you talk about how to disable it?
I also encountered this problem on wsl2.

**Comment by strawhat-dev** [comment]
@BigTear 

In `/etc/wsl.conf` (create if it doesn't exist) add:

```toml
[interop]
appendWindowsPath=false
```

Afterwards run `wsl --shutdown` and open a new session for the changes to take effect. Note that this will mean Windows executables are no longer in your `PATH`, e.g. commands like `code` will no longer work. I think this is better anyway bc it unclutters your WSL `PATH` and could prevent any problems arising from using the Windows version of something accidentally when you meant to use the Linux version. However you will manually need to re-add all the Windows executables you care about, like `code` either:

by creating an alias for the executable
```shell
alias code="/mnt/c/[your vscode installation directory]/bin/code"
```

or by creating a new script that redirects `code` to the executable
```shell
#!/usr/bin/env bash

/mnt/c/[your vscode installation directory]/bin/code "$@"
```

Also if you do that latter, remember you need to run `chmod +x` on it and make it available in your `PATH` for it to be executable from anywhere.

e.g.
```shell
echo '#!/usr/bin/env bash\n/mnt/c/[your vscode installation directory]/bin/code "$@"' > $HOME/.local/bin/code
chmod +x $HOME/.local/bin/code
```

You could also just re-add the vscode bin directory to your `PATH` variable, but I think that defeats the purpose of cleaning `/mnt/*` entries from your `PATH`.

**Comment by wallds** [comment]
https://github.com/zdharma-continuum/fast-syntax-highlighting/blob/ef8ba84c3a76c768f49a0bdd2a620b2f53c2478a/CHANGELOG.md?plain=1#L99-L108

This setting should help you, although I haven't tested it yet.
It looks similar to `zsh-syntax-highlighting.ZSH_HIGHLIGHT_DIRS_BLACKLIST`.

**Comment by jcwillox** [comment]
I've also been experimenting with disabling windows paths as @strawhat-dev showed and while it's a bit more work is at least a universal solution.
I went down the path of using symlinks for the windows executables instead, as it's simple and then they're available globally. e.g.
```bash
sudo ln -s /mnt/c/Windows/System32/cmd.exe /usr/local/bin/cmd.exe
```

I've also created this little function to still allow me to easily run windows executables. It could also be made into a bash script executable.
```bash
# facilitate windows executable interop
function exe {
    target=$(wslpath "$(awk -F$'\r' 'NR == 1 {printf "%s", $1}' <<< $(/mnt/c/Windows/System32/cmd.exe /c where $1 2>/dev/null))")
    if [[ "$target" == "." ]]; then
      echo "Command '$1' not found."
    else
        $target ${@:2}
    fi
}
```
Now, I can run anything from the windows path, with the following.
```bash
exe powershell -nop -c echo Hello World
```
It's worth noting that accessing windows exe's like this you have to pay the 130ms+ cost of resolving the path, using the full path or a link to the executable is going to be faster, but this is great for one-offs.

> This setting should help you, although I haven't tested it yet. It looks similar to `zsh-syntax-highlighting.ZSH_HIGHLIGHT_DIRS_BLACKLIST`.

Nice, that looks like what we've been looking for, I'll have to give it a try as well.
