### ISSUE TITLE
Spurious "Format of hostname incorrect" warning when scp'ing a directory whose name starts with digits

### ISSUE THREAD

**Issue by anntzer** [zdharma-continuum/fast-syntax-highlighting#20]
Typing `scp hostname:123` where 123 is the directory name (for example) prints out a spurious "Format of hostname incorrect, use -P to pass port number" warning.

**Comment by pschmitt** [comment]
This doesn't seem to relate to f-sy-h at all.

**Comment by anntzer** [comment]
Unless I am mistaken, this warning does come from f-sy-h at
https://github.com/zdharma-continuum/fast-syntax-highlighting/blob/817916dfa907d179f0d46d8de355e883cf67bd97/%E2%86%92chroma/-scp.ch#L60
