### ISSUE TITLE
Syntax Highlighting is Completely GONE 

### ISSUE THREAD

**Issue by Amarakon55** [zdharma-continuum/fast-syntax-highlighting#22]

**Comment by Amarakon55** [comment]
After I tried to apply a theme "fast-theme -t <theme>", my syntax highlighting was gone and all the text was white. Restarting zsh didn't fix this issue.

**Comment by Amarakon55** [comment]
Restarting with "fast-theme -r" fixed it but I still want to know why setting a theme doesn't work.

**Comment by vladdoster** [comment]
@Amarakon55 Did you get this resolved?

If not, please share relevant code / zinit config.

**Comment by spikespaz** [comment]
Conflicts with zsh-autocomplete if that makes any difference. Changed back to the original highlighter by @zsh-users.

**Comment by vladdoster** [comment]
@Amarakon55 please share relevant code or can this issue be closed?

**Comment by Amarakon55** [comment]
@vladdoster yes I did get it resolved.
I switched back to the default theme.
As @spikespaz said, other themes conflict with zsh-autocomplete.
I will close this issue.
