### ISSUE TITLE
Question: How can I go about replacing a specific color?

### ISSUE THREAD

**Issue by typkrft** [zdharma-continuum/fast-syntax-highlighting#25]
When I paste a string I get a white background for the pasted text, which makes it nearly impossible to see where my cursor is. This persists until I modify the command or move past the region. Changing the theme resolves it, but I'd like to keep my color scheme and avoid building a custom one. 

Example Below:

<img width="912" alt="Screen Shot 2022-04-04 at 3 53 11 PM" src="https://user-images.githubusercontent.com/12100960/161621715-54668685-2bf0-4edb-ba8f-fd00d9ec1eb6.png">

**Comment by vladdoster** [comment]
Hi @typkrft, I have had this issue as well.

Could you share your current configuration?

**Comment by vladdoster** [comment]
Add this to your `.zshrc` and see if it solves the issue.

```zsh
zle_highlight=('paste:none')
```

**Comment by vladdoster** [comment]
No worries @typkrft, I posted them within a few minutes of each other.

Glad to hear it solved the issue :^).
