### ISSUE TITLE
incorrect highlighting for ssh port forwardings

### ISSUE THREAD

**Issue by frankli0324** [zdharma-continuum/fast-syntax-highlighting#30]
as shown below:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/20221896/168466916-c2d9c49a-e2a1-416c-8735-9382e6aff74b.png">

**Comment by vladdoster** [comment]
Do you mind recreating this issue using the [bug template](https://github.com/zdharma-continuum/fast-syntax-highlighting/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5Bbug%5D%3A+)?
