### ISSUE TITLE
Questions about the `chroma` directory

### ISSUE THREAD

**Issue by DaBabyXD** [zdharma-continuum/fast-syntax-highlighting#4]
Does anyone know why there's a unicode character in front of the directory?

**Comment by agkozak** [comment]
That character was part of Sebastian's [Zsh Plugin Standard](https://github.com/zdharma-continuum/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#the-proposed-function-name-prefixes).

**Comment by DaBabyXD** [comment]
Oh, thank you. I just find it weird that there's a unicode character in this plugin.
