### ISSUE TITLE
[bug]: Syntax highlighting during completion

### ISSUE THREAD

**Issue by musjj** [zdharma-continuum/fast-syntax-highlighting#48]
### Describe the bug

When normally typing things like valid paths or arguments, they will be highlighted. But when using the auto completion system, the highlighting is gone.

### Steps to reproduce

1. Install `zsh-users/zsh-completions`
2. Type a valid path or argument, it should get highlighted
3. Re-type it using auto-completion. This time there won't be any highlighting until you press space.

### Expected behavior

Paths and arguments should still be highlighted as you complete it.

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 unknown

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

**Comment by musjj** [comment]
Looks like this feature requires a redraw hook:
https://github.com/zsh-users/zsh-syntax-highlighting/issues/654
Can we port this feature to this plugin?

**Comment by musjj** [comment]
Never mind, looks like this is caused by the fact that [jeffreytse/zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode) is lazy-loaded. This adds some surprises to the load order of my plugins, which is the source of issues like this.

The solution is to turn off lazy-loading by doing:

```zsh
ZVM_INIT_MODE=sourcing
```

**Comment by AWH1122** [comment]
Sorry, I know this is an old post but I am having the same issue. I don't have any plugins aside from this so don't think it's the same as the reason above
