### ISSUE TITLE
[bug]: wrong highlighting

### ISSUE THREAD

**Issue by QuarticCat** [zdharma-continuum/fast-syntax-highlighting#59]
### Describe the bug

![image](https://github.com/zdharma-continuum/fast-syntax-highlighting/assets/70888415/70ed20cc-1070-49e8-b87c-4a703dbc9888)

### Steps to reproduce

```console
$ git commit -m 'remove unnecessary `recv_count` / `send_count` checks'
```

### Expected behavior

The last 4 chars should have the same color as those before them.

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 unknown

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

Yakuake & xterm-256color

### If using WSL on Windows, which version of WSL

None

**Comment by HeroCC** [comment]
Isn't this a feature? 50 charachters is the generally recommended limit for git commit summaries. https://stackoverflow.com/q/2290016/1709894

**Comment by alichtman** [comment]
Yes, this is a feature, not a bug. 

(I think this is the first time I've ever posted this comment unsarcastically)

**Comment by sglbl** [comment]
is there a way to disable 50 character color limit? Since it's not mandatory and not an official git rule, I want to completely disable that.
